# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FormValidator-Simple
version:      0.02
version_from: lib/FormValidator/Simple.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Class::Data::Inheritable:      0.04
    Class::Inspector:              0
    Date::Calc:                    0
    Email::Valid:                  0
    Email::Valid::Loose:           0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
