abstract: "validation with simple chains of constraints "
author: Lyo Kato <lyo.kato@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: FormValidator-Simple
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0.22
  Class::Data::Accessor: 0.03
  Class::Data::Inheritable: 0.04
  Class::Inspector: 1.13
  Date::Calc: 5.4
  DateTime::Format::Strptime: 1.07
  Email::Valid: 0.15
  Email::Valid::Loose: 0.04
  List::MoreUtils: 0.16
  Mail::Address: 0
  Scalar::Util: 0
  Tie::IxHash: 1.21
  UNIVERSAL::require: 0.1
  YAML: 0.39
version: 0.21
